export const FETCH_CHARACTER_START = 'FETCH_CHARACTER_START'
export const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS'
export const FETCH_CHARACTER_FAIL = 'FETCH_CHARACTER_FAIL'

export const SELECT_CHARACTER = 'SELECT_CHARACTER'

export const FETCH_STARSHIP_SUCCESS = 'FETCH_STARSHIP_SUCCESS'
export const MERGE_STARSHIP = 'MERGE_STARSHIP'